spring:
  datasource:
    url: jdbc:mysql://localhost/doo?zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: ldh
    password: doo
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create
  jwt:
    secret: govlepel@$&

